[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_json = "1.0.141"
serde = { version = "1.0", features = ["derive"] }

tugfile = {path = "../tugfile"}
images = {path = "../images"}
